# Generated by Django 3.0.6 on 2020-05-24 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tagging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Element')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='tags',
            field=models.ManyToManyField(through='backend.Tagging', to='backend.Tag'),
        ),
        migrations.AddField(
            model_name='element',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to=settings.AUTH_USER_MODEL),
        ),
    ]
