# Generated by Django 3.0.6 on 2020-05-25 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200524_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='elements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Element'),
        ),
        migrations.AlterField(
            model_name='tagging',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.Tag'),
        ),
    ]
