# Generated by Django 3.0.6 on 2020-05-25 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200525_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagging',
            name='elements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Element'),
        ),
        migrations.AlterField(
            model_name='tagging',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Tag'),
        ),
    ]
