# Generated by Django 3.0.6 on 2020-11-14 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200525_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagging',
            old_name='elements',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='tagging',
            old_name='tags',
            new_name='tag',
        ),
    ]
